# Generated by Django 3.2.6 on 2021-10-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Many', '0002_alter_sandwich_sauces'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sauce',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
